name: Deploy Basic HTML site to Azure Web App - iitfelesson

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Copy files from 'site' to repo root for deployment
      - name: Copy site files to root
        run: |
          cp -r site/* .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'iitfelesson'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3A0AD92E7DAA483B9ACBBE4E3A584C5D }}